const ActionTypes = {
  FIREBASE_UPDATE: 'FIREBASE_UPDATE',
  LOGGED_IN: 'LOGGED_IN',
  LOGGED_OUT: 'LOGGED_OUT',
  UPDATE_ITEM: 'UPDATE_ITEM',
  TOGGLE_ADMIN: 'TOGGLE_ADMIN'
};
export default ActionTypes;
