const ActionTypes = {
  FIREBASE_UPDATE: 'FIREBASE_UPDATE',
  LOGGED_IN: 'LOGGED_IN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  OPEN_NEW: 'OPEN_NEW',
  UPDATE_ITEM: 'UPDATE_ITEM'
};
export default ActionTypes;
